stages:
  - test
  - build
  - deploy

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

unit-test:
  image: python:3.10
  stage: test
  script:
    - pip install -e .
    - cd $CI_PROJECT_DIR/dbcsv
    - pytest tests/unit/ -v
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "merge_request_event"

build-package:
  image: python:3.10
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - pip install build twine
    - python3 -m build .
    - twine check dist/*
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


